// src/main/components/TweetForm.svelte
<label class="tweet-main">
  <textarea id="tweet-box" class="tweet-box" bind:value="text" on:input="count()" on:paste="addImage(event)" on:keydown="keyDown(event)" autofocus></textarea>
  <span id="text-count" class="text-count { text.length > 140 ? 'invalid' : '' }">{ textCount }</span>
</label>

<ul id="image-list">
{ #each images as image, index }
  <li>
    <img class="post-image" src="{ image }" alt="" on:click="removeImage(index)">
  </li>
{ /each }
</ul>
<button id="post-button" class="post-button" on:click="post()">POST</button>

<style>
  ul {
    list-style: none;
    display: flex;
    justify-content: space-evenly;
    padding: 0;
  }

  li {
    width: 23%;
  }

  img {
    max-width: 100%;
  }

  .tweet-main {
    display: flex;
    align-items: flex-end;
  }

  .tweet-box {
    resize: none;
    width: 350px;
    height: 100px;
  }

  .post-button {
    float: right;
  }

  .text-count {
    width: 50px;
    text-align: center;
    color: black;
  }

  .invalid {
    color: red;
  }
</style>

<script>
  import * as Chrome from '../../utils/chrome/index'
  import { consumer_key, consumer_secret } from '../../../config'

  export default {
    data() {
      return {
        text: '',
        images: [],
        textCount: 140,
      }
    },

    methods: {
      addImage(event) {
        if (event.clipboardData.types[0] !== 'Files') {
          return
        }

        event.preventDefault()

        const fr = new FileReader()
        fr.onload = e => {
          const { images } = this.get()
          if (images.length >= 4) {
            return
          }

          this.set({
            images: [...images, e.target.result]
          })
        }
        for (const item of event.clipboardData.files) {
          fr.readAsDataURL(item)
        }
      },

      removeImage(index) {
        const { images } = this.get()
        images.splice(index, 1)

        this.set({
          images
        })
      },

      count() {
        const { text } = this.get()

        this.set({
          textCount: 140 - text.length
        })
      },

      keyDown(event) {
        if (event.key === 'Enter' && event.metaKey) {
          this.post()
        }
      },

      post() {
        const { users, currentUserId } = this.store.get()
        const { text, images } = this.get()
        const { access_token, access_token_secret } = users[currentUserId]

        Chrome.Runtime.sendMessage({
          keys: {
            consumer_key,
            consumer_secret,
            access_token_key: access_token,
            access_token_secret,
          },
          tweet: {
            status: text,
            media: images.map(image => image.split(',')[1]),
          },
        })

        this.set({
          text: '',
          images: [],
        })
      },
    },
  }
</script>

// src/main/components/TweetForm.tsx
import React from 'react';
import styled from 'styled-components';
import { browser } from 'webextension-polyfill-ts';

import { ImageList } from './ImageList';
import { consumer_key as consumerKey, consumer_secret as consumerSecret } from '../../../config.json';

interface TweetFormProps {
  users: Users;
  currentUserId: string;
}

interface TweetCounterProps {
  valid: boolean;
}

const TweetArea = styled.label`
  display: flex;
  align-items: flex-end;
`;

const TweetBox = styled.textarea`
  resize: none;
  width: 350px;
  height: 100px;
`;

const TweetCounter = styled.span`
  width: 50px;
  text-align: center;
  color: ${ ({ valid }: TweetCounterProps) => valid ? 'black' : 'red' };
`;

const TweetButton = styled.button`
  float: right;
`;

export const TweetForm: React.FunctionComponent<TweetFormProps> = ({
  users,
  currentUserId
}): React.ReactElement => {
  const [tweet, setTweet] = React.useState('');
  const [tweetCount, setTweetCount] = React.useState(140);
  const [images, setImages] = React.useState<Image[]>([]);

  const postTweet = (): void => {
    const { access_token, access_token_secret } = users[currentUserId];
    browser.runtime.sendMessage({
      keys: {
        consumer_key: consumerKey,
        consumer_secret: consumerSecret,
        access_token_key: access_token,
        access_token_secret,
      },
      tweet: {
        status: tweet,
        media: images.map((image) => image.split(',')[1]),
      },
    });

    setTweet('');
    setImages([]);
  };

  const handleTweetChange = (event: React.ChangeEvent<HTMLTextAreaElement>): void => {
    const { value } = event.target;
    setTweet(value);
    setTweetCount(140 - value.length);
  };

  const handlePaste = (event: React.ClipboardEvent<HTMLTextAreaElement>): void => {
    if (event.clipboardData.types[0] !== 'Files') {
      return;
    }
    event.preventDefault();

    const fileReader = new FileReader();
    fileReader.readAsDataURL(event.clipboardData.files[0]);
    fileReader.onload = () => {
      if (images.length >= 4) {
        return;
      }

      const image = fileReader.result;
      typeof image === 'string' && setImages([...images, image]);
    };

  };

  const handleKeyDown = (event: React.KeyboardEvent<HTMLTextAreaElement>): void => {
    event.key === 'Enter' && event.metaKey && postTweet();
  };

  return (
    <>
      <TweetArea>
        <TweetBox
          value={ tweet }
          autoFocus={ true }
          onChange={ (e) => handleTweetChange(e) }
          onPaste={ (e) => handlePaste(e) }
          onKeyDown={ (e) => handleKeyDown(e) }
        />
        <TweetCounter valid={ tweetCount >= 0 }>{ tweetCount }</TweetCounter>
      </TweetArea>
      <ImageList images={ images } setImages={ setImages } />
      <TweetButton onClick={ () => postTweet() }>POST</TweetButton>
    </>
  );
};
